### ISSUE TITLE
about anchors design 

### ISSUE THREAD

**Issue by ChaunceyWang** [BichenWuUCB/squeezeDet#4]
Hi, BiChen, thanks for your impressive work. 
I want to input other image resolution , but I have some problems, first , how to design the anchors? I saw the codes from **_kitti_squeezeDet_config.py_** like:
```
  H, W, B = 22, 76, 9
  anchor_shapes = np.reshape(
      [np.array(
          [[  36.,  37.], [ 366., 174.], [ 115.,  59.],
           [ 162.,  87.], [  38.,  90.], [ 258., 173.],
           [ 224., 108.], [  78., 170.], [  72.,  43.]])] * H * W,
      (H, W, B, 2)
  )
```
I know that if I use squeezeDet and input image is 1272x375， the feature map shape after **fire11** is [1,22,76,768]. Then how to calculate these numbers [  36.,  37.], [ 366., 174.]... ? If the input image is 600x600(for example)，could you give some explanations?

Besides, I noticed your reply :[https://github.com/BichenWuUCB/squeezeDet/issues/1](url), you mentioned "grid size" there, does it mean the (22,76) above? if I want to input 600*600 image,  I only need to change the "(H,W)"?  How to modify the 9 anchor_shapes?

In addition , the equation (3) in the paper seems to be different from the codes
![image](https://cloud.githubusercontent.com/assets/17997053/21647094/e616c54a-d2d3-11e6-9df7-4717158c4040.png)
I saw the code from **_imdb.py_** is
```
        delta[0] = (box_cx - mc.ANCHOR_BOX[aidx][0])/box_w
        delta[1] = (box_cy - mc.ANCHOR_BOX[aidx][1])/box_h
        delta[2] = np.log(box_w/mc.ANCHOR_BOX[aidx][2])
        delta[3] = np.log(box_h/mc.ANCHOR_BOX[aidx][3])
```
I think the code is right. there are four equations above, for the first and the second equation , the 
![image](https://cloud.githubusercontent.com/assets/17997053/21646849/e5dc493e-d2d2-11e6-9a1b-2b481ab7f759.png)  
should be 
![image](https://cloud.githubusercontent.com/assets/17997053/21647281/8f9bc520-d2d4-11e6-9105-e7f8a2bff08e.png)**?**
I am not sure……

thank you, hope for your reply！

**Comment by rainsoulsrx** [comment]
hi, I have the same question!
In the paper, the author said "We used the method described by [2] to select reference bounding box shapes to match the data distribution", I think that's to say, the anchor shape is selected according to the objects' weight and height. So when the traing data changes, the anchor shape may also need to be changed.

**Comment by BichenWuUCB** [comment]
@ChaunceyWang Thanks for your question. Responses in-line: 

> I want to input other image resolution , but I have some problems, first , how to design the anchors?

As @rainsoulsrx explained, you could refer to our [previous paper](https://arxiv.org/abs/1606.01561) on how to select an optimal set of anchors to best fits the data distribution. 

> I know that if I use squeezeDet and input image is 1272x375， the feature map shape after fire11 is [1,22,76,768]. Then how to calculate these numbers [ 36., 37.], [ 366., 174.]... ?

Anchor sizes should fit the bounding box shape distribution of your data (e.g., the shape of cars, pedestrians, cyclists, etc.). So the feature map dimension has nothing to do with anchor sizes.

> Besides, I noticed your reply :https://github.com/BichenWuUCB/squeezeDet/issues/1, you mentioned "grid size" there, does it mean the (22,76) above? if I want to input 600*600 image, I only need to change the "(H,W)"? Do I need to modify the 9 anchor_shapes?

Yes, the grid size in this case is just (22, 76). Grid size is only dependent on the original image resolution, and it is independent with anchor shape. 

> In addition , the equation (3) in the paper seems to be different from the codes ...

Yes, you are correct. I will fix this in the paper.

**Comment by cksl** [comment]
@rainsoulsrx Thanks for your reminding, I ignored the citation.
@BichenWuUCB Thanks for your reply. I saw the anchor shapes in **resnet50_convDet.py** :
```
  H, W, B = 24, 78, 9
  anchor_shapes = np.reshape(
      [np.array(
          [[  94.,  49.], [ 225., 161.], [ 170.,  91.],
           [ 390., 181.], [  41.,  32.], [ 128.,  64.],
           [ 298., 164.], [ 232.,  99.], [  65.,  42.]])] * H * W,
      (H, W, B, 2)
  ) 
```
which is different from squeezeNet before. You said: 

> Anchor sizes should fit the bounding box shape distribution of your data.  The inputs are same (KITTI dataset)

, why are the anchor shapes different?

**Comment by ChaunceyWang** [comment]
@rainsoulsrx Thanks for your reminding, I ignored the citation.
@BichenWuUCB Thanks for your reply. I saw the anchor shapes in resnet50_convDet.py :

```
  H, W, B = 24, 78, 9
  anchor_shapes = np.reshape(
      [np.array(
          [[  94.,  49.], [ 225., 161.], [ 170.,  91.],
           [ 390., 181.], [  41.,  32.], [ 128.,  64.],
           [ 298., 164.], [ 232.,  99.], [  65.,  42.]])] * H * W,
      (H, W, B, 2)
  ) 
```
which is different from squeezeNet before. You said: 

> Anchor sizes should fit the bounding box shape distribution of your data

. The inputs are same (KITTI dataset), why are the anchor shapes different?

**Comment by rainsoulsrx** [comment]
I think that's because in Res50, the feature map shape is 24*78 in that layer.

**Comment by ChaunceyWang** [comment]
@rainsoulsrx However, the feature map shape of VGG 16 in that layer is also 24*78, this is the source codes in **kitti_vgg16_config.py** 
```
  H, W, B = 24, 78, 9
  anchor_shapes = np.reshape(
      [np.array(
          [[  36.,  37.], [ 366., 174.], [ 115.,  59.],
           [ 162.,  87.], [  38.,  90.], [ 258., 173.],
           [ 224., 108.], [  78., 170.], [  72.,  43.]])] * H * W,
      (H, W, B, 2)
  )
```
But the anchor_shapes is different from ResNet50 above, is there something wrong?
And from the [paper](https://arxiv.org/abs/1606.01561)，does the anchor shape only relate to input object shape distribution ?

**Comment by BichenWuUCB** [comment]
@ChaunceyWang Yes, theoretically, res50, vgg16, squeezeDet can use the same set of anchor shapes -- as long as their inputs are the same dataset with same image resolution. The reason why you see two sets of anchor shapes is the following: KITTI evaluation script ignores objects that are smaller than a certain size (there are other criteria). So when selecting anchor shapes, we could either ignore smaller objects by following KITTI's standard, or we could keep them. We used the K-Means method described in our previous paper to choose two sets of anchors for above two cases.

It is a bit confusing that we used a different set of anchor shapes for res50 model, but the reason has nothing to do with the model or input dataset, etc. The res50 model that we released here is one of many that we trained and it happened to use a different set of anchors. 

Does it make sense?

**Comment by ChaunceyWang** [comment]
@BichenWuUCB Thank you! Roger  that!

**Comment by rainsoulsrx** [comment]
Hi, BiChen, Thanks for your patient explaination! I still have a question about the anchor size select. 


anchor_shapes = np.reshape(
      [np.array(
          [[  36.,  37.], [ 366., 174.], [ 115.,  59.],
           [ 162.,  87.], [  38.,  90.], [ 258., 173.],
           [ 224., 108.], [  78., 170.], [  72.,  43.]])] * H * W,
      (H, W, B, 2)
  )
My question is,  Is  36, 37, 366, 174 here... the anchor's weight and height relative to the image after resize? that is to say H * W(1242*375) but not the feature map? So if I chanege the image size, I should change the anchor size correspondingly  relative to the input image size but not the feature map? I do not know if I understand correctly.

**Comment by rainsoulsrx** [comment]
Hi, BiChen, I have another question.
If I have the origion training datasets whose resolution is 1920*1080 and the information in trainval.txt is also corresponding to this size, but this big size would cause the speed very slow, so I want to change the size to 450*300(for example) when training the net, that's to say, I change mc.IMAGE_WIDTH and mc.IMAGE_HEIGHT to 450 and 300, but do I need to change the information in trainval.txt at the same time? or the code will do the change automatically?

**Comment by BichenWuUCB** [comment]
@rainsoulsrx: thanks for your questions.

First question: anchor size is relative to the original image size and grid size `H, W` is also relative to the image size. Depending on the padding/striding strategies, `H,W` are roughly 1/16 of the original image height and width. So, let's say you want to down-sample your input image by half (on both width and height),  then yes, you need to down-sample your anchor size by half and you need to change grid size `H,W` to be the same as the last conv-layer output's spatial dimension. 

Second question: In my implementation, trainval.txt only contains index to images. Image resolution is specified by `mc.IMAGE_WIDTH` and `mc.IMAGE_HEIGHT` in the config file. Once you modified the two variables correctly, input images should be re-sized to the desired resolution. You don't need to (and shouldn't) specify image resolution in the trainval.txt. 

Hope that helps,
Bichen

**Comment by Imkaran** [comment]
Hi Bichen,
I have training set with image resolution of **1280x720**. When I modified the image height and width in "**kitti_model_config.py**" and "**kitti_squeezeDet_config.py**", I got the following error 

ValueError: Cannot reshape a tensor with 648000 elements to shape [10,16848,2] (336960 elements) for 'interpret_output/pred_class_probs' (op: 'Reshape') with input shapes: [324000,2], [3] and with input tensors computed as partial shapes: input[1] = [10,16848,2]. 

Can you please help me in resolving the issue
